name: Build Cryooo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17,8]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: patch
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
          git submodule update --recursive --init
          ./cryooo p
      - name: build
        run: mvn clean install javadoc:javadoc -B
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: Cryooo [Built with Java ${{ matrix.java }}]
          path: ./Cryooo-Proxy/bootstrap/target/Cryooo.jar
